# This is a basic workflow to help you get started with Actions

name: Test-Diff

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: check_tests
        name: Run test checker
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        uses: avarugh1/diff-test-run-action@main

      - name: Print output
        run: |
          echo '${{ steps.check_tests.outputs.testStatus }}';